# Generated by Django 5.0.5 on 2024-05-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='orders',
            name='phoneno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
